# Biblioteca Numpy

### Arreglos en NumPy

In [1]:
import numpy as np

data = np.random.randn(2, 3)

In [2]:
data

array([[-0.57364589,  0.76587139,  1.01378628],
       [ 1.39674426, -0.46148615,  0.54972095]])

In [3]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [4]:
print(data)
data * 10,  data + data

[[-0.57364589  0.76587139  1.01378628]
 [ 1.39674426 -0.46148615  0.54972095]]


(array([[-5.73645889,  7.65871393, 10.1378628 ],
        [13.96744258, -4.61486151,  5.49720951]]),
 array([[-1.14729178,  1.53174279,  2.02757256],
        [ 2.79348852, -0.9229723 ,  1.0994419 ]]))

Estos arreglos de numpy podemos crearlos a partir de arreglos de python, por ejemplo:


In [5]:
data = [[1,2,3], [4,5,6]]
arr = np.array(data)



Y ahora podemos utilizar operaciones como `shape` o `dim`

In [6]:
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Indexando arreglos

In [8]:
arr = np.arange(8)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr[5] # vemos el elemento en la posición 5 (contando desde el 0)

5

In [11]:
arr[2:5] # desde la pos 2 a la 4.

array([2, 3, 4])

In [12]:
arr[:] = 58 # Si asignamos un valor esto será _broadcasteado_ a todo el rango 

In [13]:
arr

array([58, 58, 58, 58, 58, 58, 58, 58])

### Slicing

In [14]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])



In [15]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[:1]

array([[1, 2, 3]])

## Hasta el arreglo en la posicion 2 sin incluir, seleccionar todos sus elementos a partir de la posicion [1] es decir: $x<2;x>1$

In [17]:
arr2d[:2, 1:] 

array([[2, 3],
       [5, 6]])

## Del arreglo en la posicion 1, seleccionar hasta su elemento en la posicion 2 sin incluirlo (aclaracion, las posiciones se cuentan desde el 0) es decir: $x1;x<2$

In [18]:
arr2d[1, :2]

array([4, 5])

## Se genera un _broadcasting_ de todos los elementos de los arreglos hasta el 2 sin incluir, empezando desde su primera posicion es decir: $x<2;x\geq1$

In [19]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Filtros booleanos

In [20]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [21]:
arr2d < 2

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]])

In [22]:
arr2d[arr2d < 2]

array([1, 0, 0, 0, 0])

In [23]:
arr2d > 0

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [24]:
arr2d[arr2d > 0]

array([1, 4, 7, 8, 9])

### Funciones universales

In [25]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
np.abs([-2, 1, -3])

array([2, 1, 3])

In [28]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [29]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Funciones de agregación

In [30]:
arr = np.random.randn(5, 4)
arr

array([[ 1.15142304,  0.8847215 ,  0.21132618,  0.0912573 ],
       [ 2.13786099, -1.46243545,  0.02613209,  0.68982236],
       [ 0.82437694, -0.07113693, -0.42851886, -0.32236196],
       [ 0.2670095 ,  0.37733601,  0.1440864 ,  0.24684147],
       [ 0.09831941,  0.79749749, -0.05480869,  0.72838752]])

In [31]:
arr.mean() # o np.mean(arr)

0.31685681577455416

In [32]:
arr.sum()

6.337136315491083